config-version: 2

sources:
  - name: raw
    database: mentorship_db
    schema: raw
    tables:
      - name: ny_taxi_yellow
        description: >
          Yellow taxi trip data. For a dictionary describing 
          green taxi data, or a map of the TLC Taxi Zones, please visit 
          [TLC Trip Record Data](https://www1.nyc.gov/site/tlc/about/tlc-trip-record-data.page)
        tags: [ny_taxi, raw, yellow]
        columns:
          - name: tpep_pickup_datetime
            description: >
              The date and time when the meter was engaged.
          - name: tpep_dropoff_datetime
            description: >
              The date and time when the meter was disengaged.
          - name: airport_fee
            description: >
              $1.25 for pick up only at LaGuardia and John F. Kennedy Airports.
          - name: vendor_id
            description: >
              A code indicating the provider that provided the record.
              Technology providers authorized under the Taxicab & Livery Passenger 
              Enhancement Programs (TPEP/LPEP)
          - name: passenger_count
            description: >
              The number of passengers in the vehicle. This is a driver-entered value.
          - name: trip_distance
            description: >
              The elapsed trip distance in miles reported by the taximeter.
          - name: pu_lockation_id
            description: >
              TLC Taxi Zone in which the taximeter was engaged
          - name: do_lockation_id
            description: >
              TLC Taxi Zone in which the taximeter was disengaged
          - name: ratecode_id
            description: >
              The final rate code in effect at the end of the trip.
          - name: store_and_fwd_flag
            description: >
              This flag indicates whether the trip record was held in vehicle
              memory before sending to the vendor, aka “store and forward,”
              because the vehicle did not have a connection to the server.
              Y = store and forward trip
              N = not a store and forward trip
          - name: payment_type
            description: >
              A numeric code signifying how the passenger paid for the trip.
          - name: fare_amount
            description: >
              The time-and-distance fare calculated by the meter.
          - name: extra
            description: >
              Miscellaneous extras and surcharges. Currently, this only includes
              the $0.50 and $1 rush hour and overnight charges.
          - name: mta_tax
            description: >
              $0.50 MTA tax that is automatically triggered based on the metered
              rate in use.
          - name: tip_amount
            description: >
              This field is automatically populated for credit card
              tips. Cash tips are not included.
          - name: improvement_surcharge
            description: >
              $0.30 improvement surcharge assessed trips at the flag drop. The
              improvement surcharge began being levied in 2015.
          - name: tolls_amount
            description: >
              Total amount of all tolls paid in trip.
          - name: total_amount
            description: >
              The total amount charged to passengers. Does not include cash tips.
          - name: congestion_surcharge
            description: >
              Total amount collected in trip for NYS congestion surcharge.
          - name: file_name
            description: >
              Path in S3 to the file where the data is stored.
          - name: file_row_number
            description: >
              Row number in the file where the data is stored.
          - name: load_dttm
            description: >
              Timestamp when the data was loaded into the table.

      - name: ny_taxi_green
        description: >
          Green taxi trip data. For a dictionary describing 
          green taxi data, or a map of the TLC Taxi Zones, please visit 
          [TLC Trip Record Data](https://www1.nyc.gov/site/tlc/about/tlc-trip-record-data.page)
        tags: [ ny_taxi, raw, green ]
        columns:
            - name: lpep_pickup_datetime
              description: >
                The date and time when the meter was engaged.
            - name: lpep_dropoff_datetime
              description: >
                The date and time when the meter was disengaged.
            - name: trip_type
              description: >
                A code indicating whether the trip was a street-hail or a dispatch
                that is automatically assigned based on the metered rate in use
                but can be altered by the driver.
                1 = Street-hail
                2 = Dispatch
            - name: vendor_id
              description: >
                A code indicating the provider that provided the record.
                Technology providers authorized under the Taxicab & Livery Passenger 
                Enhancement Programs (TPEP/LPEP)
            - name: passenger_count
              description: >
                The number of passengers in the vehicle. This is a driver-entered value.
            - name: trip_distance
              description: >
                The elapsed trip distance in miles reported by the taximeter.
            - name: pu_lockation_id
              description: >
                TLC Taxi Zone in which the taximeter was engaged
            - name: do_lockation_id
              description: >
                TLC Taxi Zone in which the taximeter was disengaged
            - name: ratecode_id
              description: >
                The final rate code in effect at the end of the trip.
            - name: store_and_fwd_flag
              description: >
                This flag indicates whether the trip record was held in vehicle
                memory before sending to the vendor, aka “store and forward,”
                because the vehicle did not have a connection to the server.
                Y = store and forward trip
                N = not a store and forward trip
            - name: payment_type
              description: >
                A numeric code signifying how the passenger paid for the trip.
            - name: fare_amount
              description: >
                The time-and-distance fare calculated by the meter.
            - name: extra
              description: >
                Miscellaneous extras and surcharges. Currently, this only includes
                the $0.50 and $1 rush hour and overnight charges.
            - name: mta_tax
              description: >
                $0.50 MTA tax that is automatically triggered based on the metered
                rate in use.
            - name: tip_amount
              description: >
                This field is automatically populated for credit card
                tips. Cash tips are not included.
            - name: improvement_surcharge
              description: >
                $0.30 improvement surcharge assessed trips at the flag drop. The
                improvement surcharge began being levied in 2015.
            - name: tolls_amount
              description: >
                Total amount of all tolls paid in trip.
            - name: total_amount
              description: >
                The total amount charged to passengers. Does not include cash tips.
            - name: congestion_surcharge
              description: >
                Total amount collected in trip for NYS congestion surcharge.
            - name: file_name
              description: >
                Path in S3 to the file where the data is stored.
            - name: file_row_number
              description: >
                Row number in the file where the data is stored.
            - name: load_dttm
              description: >
                Timestamp when the data was loaded into the table.

      - name: ny_taxi_zones
        description: >
          TLC Taxi Zones
        tags: [ ny_taxi, raw, zones ]
        columns:
          - name: location_id
            description: >
              The taxi zone in which the trip started or ended.
          - name: borough
            description: >
              The borough in which the taxi zone is located.
          - name: zone
            description: >
              The name of the taxi zone.
          - name: service_zone
            description: >
              The service zone of the taxi zone.
          - name: file_name
            description: >
              Path in S3 to the file where the data is stored.
          - name: file_row_number
            description: >
              Row number in the file where the data is stored.
          - name: load_dttm
            description: >
              Timestamp when the data was loaded into the table.
