USE ROLE SYSADMIN;

CREATE OR REPLACE WAREHOUSE mentorship_dwh
WITH
WAREHOUSE_TYPE = STANDARD
WAREHOUSE_SIZE = SMALL
INITIALLY_SUSPENDED = TRUE
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
COMMENT = 'Compute warehouse for mentorship project';
